service: chapter3-todo
frameworkVersion: ">=1.30.0"
plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-dotenv-plugin
custom:
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-1'}
  accountid: ${env:AWS_ACCOUNT_ID}
  poolArn: ${env:CHAPTER3_POOL_ARN}
  domain: ${env:CHAPTER3_DOMAIN}
  dotenv:
    path: ../.env
  customDomain:
    domainName: 'chapter3api.${self:custom.domain}'
    stage: ${self:provider.stage}
    basePath: api
    certificateName: '*.${self:custom.domain}'
    createRoute53Record: true
    endpointType: regional
  serverless-offline:
    port: 3000

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-1'}
  environment:
    TODO_TABLE: '${self:service}-${self:provider.stage}'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:custom.region}:${self:custom.accountid}:*"

functions:
  create:
    handler: handler.create
    events:
      - http:
          method: POST
          path: todo
          cors: true
          authorizer:
            arn: '${self:custom.poolArn}'
  read:
    handler: handler.read
    events:
      - http:
          method: GET
          path: todo/{id}
          cors: true
          authorizer:
            arn: '${self:custom.poolArn}'
  update:
    handler: handler.update
    events:
      - http:
          method: PUT
          path: todo/{id}
          cors: true
          authorizer:
            arn: '${self:custom.poolArn}'
  delete:
    handler: handler.delete
    events:
      - http:
          method: DELETE
          path: todo/{id}
          cors: true
          authorizer:
            arn: '${self:custom.poolArn}'
  list:
    handler: handler.list
    events:
      - http:
          method: GET
          path: todo
          cors: true
          authorizer:
            arn: '${self:custom.poolArn}'

resources:
  - ${file(./dynamodb.yml)}

